# Database
db.url=jdbc:postgresql://postgres:5432/bank_db
db.username=postgres
db.password=postgres
db.driver.class=org.postgresql.Driver

# Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.hbm2ddl.auto=update

# Kafka
kafka.bootstrap.servers=kafka1:9092,kafka2:9093,kafka3:9094
kafka.consumer.group.id=bank-consumer-group
